/**
 * This class is generated by jOOQ
 */
package com.example.domain;


import com.example.domain.tables.Person;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.person</code>.
     */
    public static final Person PERSON = com.example.domain.tables.Person.PERSON;
}
